"""add edited_report_html to applications

Revision ID: f4a0318e8f26
Revises: 17b3306be507
Create Date: 2026-09-14 12:57:03.331081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a0318e8f26'
down_revision: Union[str, Sequence[str], None] = '17b3306be507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('edited_report_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'edited_report_html')
    # ### end Alembic commands ###
